### ISSUE TITLE
0.61 checklist

### ISSUE THREAD

**Issue by MoOx** [reason-react-native/reason-react-native#625]
https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#0610

What I see here in short is

- [x] useWindowDimensions [done](https://github.com/reason-react-native/reason-react-native/pull/615)
- [x] SoundManager & Deprecate method UIManagerModule.playTouchSound [done](https://github.com/reason-react-native/reason-react-native/pull/616)
- [ ] Make Animation EndCallback type allow any return value (**do we need to do something here?** I don't like this idea)
- [ ] update template (flow & react version)

Thanks @sgny for doing the hard work here 😍

I guess we could ship 0.61 next week! (I prefer to have a small delay with 0.60.1 so people don't feel overwhelmed.

**Comment by MoOx** [comment]
I also want to migrate the website for this release to our organisation url :)

**Comment by tlvenn** [comment]
Bonjour @MoOx , is there any chance to ship 0.61 soon ?
The prospect of leveraging fast refresh is quite appealing ;)

Thanks !

**Comment by MoOx** [comment]
Will do ASAP yeah

**Comment by MoOx** [comment]
If you are not relying on breaking changes listed above you can use RN 0.61 with 0.60 bindings

**Comment by MoOx** [comment]
I will handle a batch of releases today, lots of package need to be released.

**Comment by sgny** [comment]
New website, thanks!

**Comment by MoOx** [comment]
:) I moved the engine to https://github.com/reason-react-native/reason-react-native.github.io & it use the md files from the `reason-react-native` package.

**Comment by MoOx** [comment]
I still have to make some update for the template, but I am closing this as it's mostly ok.
